# Generated by Django 6.0 on 2026-01-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Name',
            field=models.CharField(default='Product', max_length=40),
        ),
    ]
