# Generated by Django 6.0 on 2026-01-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='about',
            new_name='About',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='Name',
        ),
    ]
