# Generated by Django 6.0 on 2026-01-07 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_rename_about_category_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='Is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
