# Generated by Django 6.0 on 2026-01-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
