# Generated by Django 6.0 on 2026-01-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_cart_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Quantiy',
            new_name='Quantitpythomy',
        ),
    ]
