# Generated by Django 6.0 on 2026-01-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_rename_quantiy_cartitem_quantitpythomy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Quantitpythomy',
            new_name='Quantity',
        ),
    ]
