# Generated by Django 6.0 on 2026-01-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_rename_quantity_cartitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
